# Base configs
baseurl: "https://pugga12.github.io/portfolio/"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography by Adam Aptowitz"
subtitle: ""
author: "Adam Aptowitz"
header:
 title: "Photography"
 subtitle: "by Adam Aptowitz"
footer:
 name: "Hey there, my name is Adam"
 bio: "I am a photographer, software engineer, and roboticist from Queens, New York. I made this website to share the many thousands of photos I took over the last 3 years."
 github: "I use an open-source project from Ram Patra to host this website. Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork this repo on github</a> ;)"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}, {"tag": "LensModel", "icon": "eye"}]'
social_urls:
  instagram: "https://www.instagram.com/notaddypug"
  linkedin: "https://in.linkedin.com/in/adam-aptowitz"
  github: "https://www.github.com/Pugga12"
